# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [ ]:
import numpy as np
import random as rand

In [ ]:
#01

arr = np.random.randint(1,20,size=(5,5))
print(f"Original Array :\n{arr}")

#replacea all element in third column with 1
arr[:, 2]= 1
print(f"Updeted Array:\n{arr}")





Original Array :
[[ 7 10 12  9 16]
 [18 11  9  9 13]
 [ 1 19 14  7 19]
 [10  9  8 17  1]
 [ 5 15  6 15  2]]
Updeted Array:
[[ 7 10  1  9 16]
 [18 11  1  9 13]
 [ 1 19  1  7 19]
 [10  9  1 17  1]
 [ 5 15  1 15  2]]


In [22]:
#02
arr2 = np.arange(1,17).reshape((4,4))
print(f"Original Array:\n{arr2}")

#diagonl element with 0
np.fill_diagonal(arr2,0)
print(f"Updeted Array:\n{arr2}")

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Updeted Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [42]:
arr =np.arange(1,37).reshape((6,6))
print(f"Original Array:\n{arr}")

#extracting array
print("Extracted array of the 3rd to 5th rows and 2nd to 4th columns:")
print(arr[3:5,2:4])

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Extracted array of the 3rd to 5th rows and 2nd to 4th columns:
[[21 22]
 [27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [54]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate(
    (array[0, :],
    array[-1, :], 
    array[1:-1, 0], 
    array[1:-1, -1])
)
print("Border elements:")
print(border_elements)

Original array:
[[ 2 14 10 12  3]
 [ 1 19  3  3  9]
 [17 14 16 19  6]
 [16  5  1  2 19]
 [20  7  9  5 15]]
Border elements:
[ 2 14 10 12  3 20  7  9  5 15  1 17 16  9  6 19]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [5]:
array1 =np.random.randint(1,13,size=(3,4))
array2 =np.random.randint(1,13,size=(3,4))

print(f"Array 1:\n{array1} \nArray 2:\n{array2}")

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 1 10 12  6]
 [12  8  5  6]
 [ 8  7  7  5]] 
Array 2:
[[ 2  4  4  3]
 [ 8  8  3  6]
 [ 8  7 11  1]]
Element-wise addition:
[[ 3 14 16  9]
 [20 16  8 12]
 [16 14 18  6]]
Element-wise subtraction:
[[-1  6  8  3]
 [ 4  0  2  0]
 [ 0  0 -4  4]]
Element-wise multiplication:
[[ 2 40 48 18]
 [96 64 15 36]
 [64 49 77  5]]
Element-wise division:
[[0.5        2.5        3.         2.        ]
 [1.5        1.         1.66666667 1.        ]
 [1.         1.         0.63636364 5.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
array = np.arange(1,17).reshape(4,4)
print(array)

row_sum = np.sum(array,axis=1)
column_sum = np.sum(array,axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [ ]:
array1 =np.random.randint(1,26,size=(5,5))
print(array1)

print(f"Mean: {np.mean(array1)}\nMedian: {np.median(array1)}\nStandard Deviation:{np.std(array1)}\nVariance: {np.var(array1)}")

[[23  2  8 19  8]
 [ 7  5  5  1  5]
 [20 11  7  4  2]
 [20  6 22 15  1]
 [12 18 13  2 25]]
Mean: 10.44
Median: 8.0
Standard Deviation:7.547608892887866
Variance: 56.9664


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [15]:
array = np.arange(1,10).reshape(3,3)
print(array)

mean = np.mean(array)
std_dev = np.std(array)

normalized_array = (array-mean)/std_dev
print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [25]:
array = np.random.randint(1,10,size=(3,3))
row_arr = np.random.randint(1,10,size=(3,))

print(f"Array:\n{array}")
print(f"Row Array:\n{row_arr}")

#Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
adding = array + row_arr
print(f"Add a 1D array of shape (3,) to each row of the 2D array using broadcasting:\n{adding}")



Array:
[[9 6 4]
 [8 5 7]
 [1 8 9]]
Row Array:
[9 6 2]
Add a 1D array of shape (3,) to each row of the 2D array using broadcasting:
[[18 12  6]
 [17 11  9]
 [10 14 11]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [37]:
array = np.random.randint(1,11,size=(4,4))
row_array = np.random.randint(1,11,size=(4,))
print(f"Array:\n{array}")
print(f"1D Array:\n{row_array}")

sub = array - row_array
print(sub)


Array:
[[ 9  7  9  5]
 [ 1  1  1 10]
 [ 6  2 10  7]
 [ 9  2  5  1]]
1D Array:
[2 7 2 3]
[[ 7  0  7  2]
 [-1 -6 -1  7]
 [ 4 -5  8  4]
 [ 7 -5  3 -2]]


In [38]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Flatten the array
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

# Reshape the array back to (5, 5)
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Original array:
[[ 1 12 18 16 18]
 [ 7 10 14  1  5]
 [19  6  7  3  3]
 [ 4 16 17 16  9]
 [ 4  5 16 15 14]]
Flattened array:
[ 1 12 18 16 18  7 10 14  1  5 19  6  7  3  3  4 16 17 16  9  4  5 16 15
 14]
Reshaped array:
[[ 1 12 18 16 18]
 [ 7 10 14  1  5]
 [19  6  7  3  3]
 [ 4 16 17 16  9]
 [ 4  5 16 15 14]]


In [39]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[ 1 12 11 15  2]
 [ 7 20 16 12  6]
 [ 8  2  7 18 19]
 [ 4 10 14 12  1]
 [20 16  8  4  3]]
Corner elements:
[ 1  2 20  3]


In [40]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[10 15 20 16]
 [20  7  2 10]
 [ 6 14  5 16]
 [ 9 18 17 14]]
Modified array:
[[10 10 10 10]
 [10  7  2 10]
 [ 6 10  5 10]
 [ 9 10 10 10]]


In [48]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]
