# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np
import random as rand

In [ ]:
#01

arr = np.random.randint(1,20,size=(5,5))
print(f"Original Array :\n{arr}")

#replacea all element in third column with 1
arr[:, 2]= 1
print(f"Updeted Array:\n{arr}")





Original Array :
[[ 7 10 12  9 16]
 [18 11  9  9 13]
 [ 1 19 14  7 19]
 [10  9  8 17  1]
 [ 5 15  6 15  2]]
Updeted Array:
[[ 7 10  1  9 16]
 [18 11  1  9 13]
 [ 1 19  1  7 19]
 [10  9  1 17  1]
 [ 5 15  1 15  2]]


In [22]:
#02
arr2 = np.arange(1,17).reshape((4,4))
print(f"Original Array:\n{arr2}")

#diagonl element with 0
np.fill_diagonal(arr2,0)
print(f"Updeted Array:\n{arr2}")

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Updeted Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [42]:
arr =np.arange(1,37).reshape((6,6))
print(f"Original Array:\n{arr}")

#extracting array
print("Extracted array of the 3rd to 5th rows and 2nd to 4th columns:")
print(arr[3:5,2:4])

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Extracted array of the 3rd to 5th rows and 2nd to 4th columns:
[[21 22]
 [27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [54]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate(
    (array[0, :],
    array[-1, :], 
    array[1:-1, 0], 
    array[1:-1, -1])
)
print("Border elements:")
print(border_elements)

Original array:
[[ 2 14 10 12  3]
 [ 1 19  3  3  9]
 [17 14 16 19  6]
 [16  5  1  2 19]
 [20  7  9  5 15]]
Border elements:
[ 2 14 10 12  3 20  7  9  5 15  1 17 16  9  6 19]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.