In [4]:
pip install  numpy


  Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.5-cp313-cp313-win_amd64.whl (12.8 MB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


In [4]:
# slicing 
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(arr[1][2])
print(arr[0:2,1:])
print(arr[1][1])

6
[[2 3]
 [5 6]]
5
